-- Migration: Add missing fields for high-fidelity bill printing
ALTER TABLE shops ADD COLUMN IF NOT EXISTS account_id VARCHAR(50);
ALTER TABLE shops ADD COLUMN IF NOT EXISTS permit_numbers TEXT; -- e.g. TABC Permits

ALTER TABLE items ADD COLUMN IF NOT EXISTS sku VARCHAR(50);
ALTER TABLE items ADD COLUMN IF NOT EXISTS upc VARCHAR(50);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS load_number VARCHAR(50);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_credits DECIMAL(12, 2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS total_deposit DECIMAL(12, 2) DEFAULT 0.00;

ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_discount DECIMAL(10, 2) DEFAULT 0.00;
ALTER TABLE order_items ADD COLUMN IF NOT EXISTS unit_deposit DECIMAL(10, 2) DEFAULT 0.00;
