const fs = require('fs');
const path = require('path');
const PDFDocument = require('pdfkit');

const uploadsDir = path.join(__dirname, '../uploads');
const billsDir = path.join(uploadsDir, 'bills');

const companyProfile = {
  name: process.env.BILL_COMPANY_NAME || 'Vendor Management',
  addressLine1: process.env.BILL_COMPANY_ADDRESS_LINE_1 || 'PO BOX 000000',
  addressLine2: process.env.BILL_COMPANY_ADDRESS_LINE_2 || 'Dallas, TX 75201',
  phone: process.env.BILL_COMPANY_PHONE || '(000) 000-0000',
  license: process.env.BILL_COMPANY_LICENSE || '',
  legalText: process.env.BILL_LEGAL_TEXT || 'This invoice was generated by the Vendor Management backend.',
};

const ensureBillsDir = () => {
  fs.mkdirSync(billsDir, { recursive: true });
};

const toNumber = (value) => {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : 0;
};

const formatCurrency = (value) => toNumber(value).toFixed(2);

const formatDateTime = (value) => {
  const date = value ? new Date(value) : new Date();

  if (Number.isNaN(date.getTime())) {
    return '';
  }

  return date.toLocaleString('en-US', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
    hour: 'numeric',
    minute: '2-digit',
  });
};

const sanitizeSegment = (value) => {
  const sanitized = String(value || '')
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

  return sanitized || 'bill';
};

const splitAddress = (value) => {
  if (!value) {
    return [];
  }

  return String(value)
    .split(/\r?\n|,/)
    .map((line) => line.trim())
    .filter(Boolean);
};

const buildFileName = (order) => {
  const orderPart = sanitizeSegment(order.order_number || order.id);
  const customerPart = sanitizeSegment(order.account_id || order.customer_id || 'customer');
  return `invoice-${orderPart}-${customerPart}.pdf`;
};

const getBillMeta = (fileName) => ({
  file_name: fileName,
  file_path: `bills/${fileName}`,
  bill_link: `/files/bills/${encodeURIComponent(fileName)}`,
});

const drawLine = (doc, y) => {
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;
  doc.moveTo(left, y).lineTo(right, y).dash(4, { space: 2 }).stroke();
  doc.undash();
};

const ensureSpace = (doc, height, onPageBreak) => {
  const bottomLimit = doc.page.height - doc.page.margins.bottom;
  if (doc.y + height <= bottomLimit) {
    return;
  }

  doc.addPage();
  doc.font('Courier').fontSize(10);

  if (typeof onPageBreak === 'function') {
    onPageBreak();
  }
};

const addSectionTitle = (doc, title) => {
  doc.moveDown(0.6);
  doc.font('Courier-Bold').fontSize(12).text(title, { align: 'center' });
  doc.moveDown(0.4);
};

const renderItemsHeader = (doc, columns) => {
  drawLine(doc, doc.y);
  doc.moveDown(0.4);
  doc.font('Courier-Bold').fontSize(10);
  const top = doc.y;

  columns.forEach((column) => {
    doc.text(column.label, column.x, top, {
      width: column.width,
      align: column.align || 'left',
    });
  });

  doc.moveDown(0.6);
  drawLine(doc, doc.y);
  doc.moveDown(0.4);
  doc.font('Courier').fontSize(10);
};

const renderItemsTable = (doc, order) => {
  const columns = [
    { label: 'ITEM#', x: 36, width: 46 },
    { label: 'QTY', x: 82, width: 28, align: 'right' },
    { label: 'DESCRIPTION', x: 114, width: 178 },
    { label: 'U.P.C.', x: 292, width: 86 },
    { label: 'PRICE', x: 378, width: 46, align: 'right' },
    { label: 'DISC', x: 424, width: 40, align: 'right' },
    { label: 'DEP', x: 464, width: 32, align: 'right' },
    { label: 'AMOUNT', x: 496, width: 80, align: 'right' },
  ];

  renderItemsHeader(doc, columns);

  if (!order.items.length) {
    doc.text('No order items found.', 36, doc.y, { width: 540, align: 'center' });
    doc.moveDown(1);
    drawLine(doc, doc.y);
    return;
  }

  order.items.forEach((item) => {
    const description = [item.description_name, item.quantity_size].filter(Boolean).join(' ');
    const rowHeight = Math.max(
      18,
      doc.heightOfString(description || '-', { width: 178 })
    ) + 2;

    ensureSpace(doc, rowHeight + 20, () => renderItemsHeader(doc, columns));

    const top = doc.y;
    const values = [
      { x: 36, width: 46, text: item.item_number || item.item_id || '-', align: 'left' },
      { x: 82, width: 28, text: String(item.quantity || 0), align: 'right' },
      { x: 114, width: 178, text: description || '-', align: 'left' },
      { x: 292, width: 86, text: item.upc || '-', align: 'left' },
      { x: 378, width: 46, text: formatCurrency(item.unit_price), align: 'right' },
      { x: 424, width: 40, text: formatCurrency(item.unit_discount), align: 'right' },
      { x: 464, width: 32, text: formatCurrency(item.unit_deposit), align: 'right' },
      { x: 496, width: 80, text: formatCurrency(item.subtotal), align: 'right' },
    ];

    values.forEach((value) => {
      doc.text(value.text, value.x, top, {
        width: value.width,
        align: value.align,
      });
    });

    doc.y = top + rowHeight;
  });

  drawLine(doc, doc.y);
};

const renderTotals = (doc, order) => {
  const totalUnits = order.items.reduce((sum, item) => sum + toNumber(item.quantity), 0);
  const totalSales = toNumber(order.total_amount);
  const totalCredits = toNumber(order.total_credits);
  const totalDeposit = toNumber(order.total_deposit);
  const invoiceTotal = totalSales - totalCredits + totalDeposit;

  ensureSpace(doc, 150);
  doc.moveDown(0.8);
  doc.font('Courier').fontSize(10);

  const summaryTop = doc.y;
  doc.text(`Line Items: ${order.items.length}`, 36, summaryTop);
  doc.text(`Units: ${totalUnits}`, 36, summaryTop + 16);
  doc.text(`Credits: ${formatCurrency(totalCredits)}`, 36, summaryTop + 32);
  doc.text(`Deposits: ${formatCurrency(totalDeposit)}`, 36, summaryTop + 48);

  const totalsX = 360;
  doc.text('Total Sales', totalsX, summaryTop, { width: 120, align: 'right' });
  doc.text(formatCurrency(totalSales), 490, summaryTop, { width: 86, align: 'right' });
  doc.text('Total Credits', totalsX, summaryTop + 18, { width: 120, align: 'right' });
  doc.text(formatCurrency(totalCredits), 490, summaryTop + 18, { width: 86, align: 'right' });
  doc.text('Total Deposit', totalsX, summaryTop + 36, { width: 120, align: 'right' });
  doc.text(formatCurrency(totalDeposit), 490, summaryTop + 36, { width: 86, align: 'right' });

  drawLine(doc, summaryTop + 60);
  doc.font('Courier-Bold');
  doc.text('Invoice Total', totalsX, summaryTop + 68, { width: 120, align: 'right' });
  doc.text(formatCurrency(invoiceTotal), 490, summaryTop + 68, { width: 86, align: 'right' });
  doc.font('Courier');

  doc.y = summaryTop + 98;
};

const renderPaymentSection = (doc, order) => {
  ensureSpace(doc, 90);
  addSectionTitle(doc, 'PAYMENT');
  drawLine(doc, doc.y);
  doc.moveDown(0.4);
  doc.font('Courier-Bold').fontSize(10);
  const headerTop = doc.y;
  doc.text('INVOICE#', 36, headerTop, { width: 110 });
  doc.text('PAYMENT TYPE', 180, headerTop, { width: 140 });
  doc.text('AMOUNT', 380, headerTop, { width: 196, align: 'right' });
  doc.moveDown(0.6);
  drawLine(doc, doc.y);
  doc.moveDown(0.4);
  doc.font('Courier').fontSize(10);
  const invoiceTotal = toNumber(order.total_amount) - toNumber(order.total_credits) + toNumber(order.total_deposit);
  const rowTop = doc.y;
  doc.text(order.order_number || '-', 36, rowTop, { width: 110 });
  doc.text(order.payment_type || 'Charge', 180, rowTop, { width: 140 });
  doc.text(formatCurrency(invoiceTotal), 380, rowTop, { width: 196, align: 'right' });
  doc.moveDown(1.6);
};

const renderSignatures = (doc, order) => {
  ensureSpace(doc, 120);
  drawLine(doc, doc.y);
  doc.moveDown(0.8);
  doc.font('Courier-Bold').fontSize(10);
  const titleTop = doc.y;
  doc.text('Customer Signature', 36, titleTop, { width: 220 });
  doc.text('Driver Signature', 320, titleTop, { width: 220 });
  doc.moveDown(2.4);
  doc.font('Courier').fontSize(10);
  const lineTop = doc.y;
  doc.text('______________________________', 36, lineTop, { width: 220 });
  doc.text('______________________________', 320, lineTop, { width: 220 });
  doc.moveDown(0.4);
  const nameTop = doc.y;
  doc.text(order.dba || order.customer_name || '-', 36, nameTop, { width: 220, align: 'center' });
  doc.text(order.salesrep_name || '-', 320, nameTop, { width: 220, align: 'center' });
  doc.moveDown(1.2);
};

const renderHeader = (doc, order) => {
  doc.font('Courier-Bold').fontSize(16).text(companyProfile.name, { align: 'center' });
  doc.font('Courier').fontSize(10);
  doc.text(companyProfile.addressLine1, { align: 'center' });
  doc.text(companyProfile.addressLine2, { align: 'center' });
  doc.text(companyProfile.phone, { align: 'center' });

  if (companyProfile.license) {
    doc.text(companyProfile.license, { align: 'center' });
  }

  doc.moveDown(0.8);

  const blockTop = doc.y;
  const customerLines = [
    `Account: ${order.account_id || '-'}`,
    order.dba || order.customer_name || '-',
    ...(order.registered_company_name ? [order.registered_company_name] : []),
    ...splitAddress(order.customer_address),
    order.customer_phone || '',
    order.permit_numbers ? `Permit #: ${order.permit_numbers}` : '',
    order.tobacco_permit_number ? `Tobacco Permit #: ${order.tobacco_permit_number}` : '',
  ].filter(Boolean);

  const metaLines = [
    `Date: ${formatDateTime(order.created_at)}`,
    `Invoice#: ${order.order_number || order.id}`,
    `PO#: ${order.customer_id || '-'}`,
    `Load: ${order.load_number || '-'}`,
    `Terms: ${order.payment_type || 'Charge'}`,
    `Driver: ${order.salesrep_name || '-'}`,
    `Salesrep: ${order.salesrep_name || '-'}`,
    `Salesrep Cell #: ${order.salesrep_phone || '-'}`,
  ];

  doc.text(customerLines.join('\n'), 36, blockTop, { width: 240 });
  doc.text(metaLines.join('\n'), 310, blockTop, { width: 266 });

  doc.y = Math.max(doc.y, blockTop + 124);
  doc.moveDown(0.6);
};

const renderFooterText = (doc) => {
  ensureSpace(doc, 80);
  drawLine(doc, doc.y);
  doc.moveDown(0.8);
  doc.font('Courier').fontSize(9).text(companyProfile.legalText, 36, doc.y, {
    width: 540,
    align: 'justify',
  });
};

const generateOrderBill = async (order) => {
  ensureBillsDir();

  const fileName = buildFileName(order);
  const filePath = path.join(billsDir, fileName);

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({
      size: 'LETTER',
      margin: 36,
      info: {
        Title: `Invoice ${order.order_number || order.id}`,
        Author: companyProfile.name,
      },
    });
    const stream = fs.createWriteStream(filePath);

    stream.on('finish', () => {
      resolve({
        ...getBillMeta(fileName),
        generated_at: new Date().toISOString(),
      });
    });
    stream.on('error', reject);
    doc.on('error', reject);

    doc.pipe(stream);
    doc.font('Courier').fontSize(10);

    renderHeader(doc, order);
    renderItemsTable(doc, order);
    renderTotals(doc, order);
    renderPaymentSection(doc, order);
    renderSignatures(doc, order);
    renderFooterText(doc);

    doc.end();
  });
};

module.exports = {
  generateOrderBill,
};
